name: Packer GCP Build & Auto Destroy

on:
  push:
    branches:
      - main
      - sai
      - feature/sai
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  packer-build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.packer.outputs.image_name }}

    env:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: root

    steps:
      - uses: actions/checkout@v4

      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/516216943908/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-ci-sa@packer-automation-483407.iam.gserviceaccount.com


      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2   

      - name: Validate GCP authentication
        run: |
             gcloud auth list

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible deps
        run: pip install ansible passlib

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.9.2"  # pin the version

     
      - name: Install Vault
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common curl unzip
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
            | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vault

      - name: Start Vault
        run: |
          vault server -dev -dev-root-token-id=root > vault.log 2>&1 &
          sleep 5

      - name: Configure Vault Secrets
        run: |
          vault kv put secret/packer/ansible \
            admin_password="${{ secrets.ADMIN_PASSWORD }}" \
            user1_password="${{ secrets.USER1_PASSWORD }}"

      - name: Create Packer vars
        run: |
          cat <<EOF > packer_template_gcp/secrets.auto.pkrvars.hcl
          admin_password = "$(vault kv get -field=admin_password secret/packer/ansible)"
          user1_password = "$(vault kv get -field=user1_password secret/packer/ansible)"
          EOF

      - name: Packer Build
        id: packer
        run: |
          packer init packer_template_gcp
          packer build packer_template_gcp | tee packer.log
          IMAGE_NAME=$(grep -oP "packer-[^ ]+" packer.log | tail -1)
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

  terraform-deploy-destroy:
    runs-on: ubuntu-latest
    needs: packer-build
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/516216943908/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-ci-sa@packer-automation-483407.iam.gserviceaccount.com
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
  
      - name: Generate SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
          echo "SSH_PUBLIC_KEY=$(cat ~/.ssh/id_ed25519.pub)" >> $GITHUB_ENV
  
      - name: Terraform Apply
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_TOKEN }}
        run: |
          cd terraform-gcp
          terraform init
          terraform apply \
            -var="image_name=${{ needs.packer-build.outputs.image_name }}" \
            -var="ssh_public_key=${SSH_PUBLIC_KEY}" \
            -auto-approve
            
      - name: Validate VM Users & Permissions
        env:
           TF_TOKEN_app_terraform_io: ${{ secrets.TFC_TOKEN }}
        run: |
          chmod +x .vscode/scripts/verify_users.sh
          ./.vscode/scripts/verify_users.sh
  
      - name: Wait 2 minutes
        run: sleep 120
          #sleep got 2 minutes
      - name: Terraform Destroy
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_TOKEN }}
        run: |
          cd terraform-gcp
          terraform destroy \
            -var="image_name=${{ needs.packer-build.outputs.image_name }}" \
            -var="ssh_public_key=${SSH_PUBLIC_KEY}" \
            -auto-approve
